using System.Text;
using SecKit.Core;
using SecKit.Models;

namespace SecKit.Modules.Reporting;

/// <summary>
/// Generates Snort and Suricata IDS/IPS rules from attack patterns discovered during scanning.
/// </summary>
public class IdsExporter
{
    private readonly string _outputDir;
    private int _snortSid = 1000001;

    public IdsExporter(string outputDir)
    {
        _outputDir = Path.Combine(outputDir, "reports");
        Directory.CreateDirectory(_outputDir);
    }

    /// <summary>
    /// Generates Snort and Suricata rule files from vulnerability findings.
    /// </summary>
    public async Task<IdsReport> GenerateAsync(IEnumerable<Vulnerability> vulnerabilities)
    {
        var vulns = vulnerabilities.ToList();
        var report = new IdsReport();

        if (vulns.Count == 0)
        {
            Logger.Info("No vulnerabilities provided; skipping IDS rule generation.");
            return report;
        }

        // Generate Snort rules
        var snortPath = Path.Combine(_outputDir, "snort.rules");
        var snortRules = GenerateSnortRules(vulns);
        await File.WriteAllTextAsync(snortPath, snortRules);
        report.SnortPath = snortPath;
        report.SnortRuleCount = snortRules.Split('\n').Count(l => l.StartsWith("alert "));

        // Generate Suricata rules (same format, different output file)
        var suricataPath = Path.Combine(_outputDir, "suricata.rules");
        var suricataRules = GenerateSuricataRules(vulns);
        await File.WriteAllTextAsync(suricataPath, suricataRules);
        report.SuricataPath = suricataPath;
        report.SuricataRuleCount = suricataRules.Split('\n').Count(l => l.StartsWith("alert "));

        Logger.Info($"IDS rules generated: Snort={report.SnortRuleCount}, Suricata={report.SuricataRuleCount}");
        return report;
    }

    #region Snort Rules

    private string GenerateSnortRules(List<Vulnerability> vulns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ================================================================");
        sb.AppendLine("# Snort IDS Rules — Generated by SecKit");
        sb.AppendLine($"# Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"# Rules generated from {vulns.Count} vulnerability findings");
        sb.AppendLine("# ================================================================");
        sb.AppendLine();

        foreach (var v in vulns.OrderBy(v => v.Severity))
        {
            switch (v.Type.ToLowerInvariant())
            {
                case "sql injection":
                case "sqli":
                    GenerateSnortSqli(sb, v);
                    break;
                case "xss":
                case "cross-site scripting":
                    GenerateSnortXss(sb, v);
                    break;
                case "path traversal":
                case "directory traversal":
                    GenerateSnortPathTraversal(sb, v);
                    break;
                case "command injection":
                case "os command injection":
                    GenerateSnortCommandInjection(sb, v);
                    break;
                case "ssrf":
                case "server-side request forgery":
                    GenerateSnortSsrf(sb, v);
                    break;
            }
        }

        return sb.ToString();
    }

    private void GenerateSnortSqli(StringBuilder sb, Vulnerability v)
    {
        var msg = $"SQL Injection Attempt — {v.Severity} finding on {v.Url}";
        var classification = v.Severity switch { "Critical" => "Attempted Administrator Privilege Gain", "High" => "Web Application Attack", _ => "Web Application Attack" };
        var priority = v.Severity switch { "Critical" => 1, "High" => 2, _ => 3 };

        sb.AppendLine($"# Rule: SQLi — {v.Url} (Confidence: {v.Confidence}%)");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"{msg}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  content:\"union\"; nocase; http_uri;");
        sb.AppendLine($"  content:\"select\"; nocase; http_uri; distance:0;");
        sb.AppendLine($"  metadata:service http, seckit-sqli;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:{classification};");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:{priority};");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;

        sb.AppendLine($"# Rule: SQLi — OR 1=1 pattern");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"SQL Injection — Boolean-based OR 1=1\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  pcre:\"/[?&][^=]+=(%27|')(%20|\\s)*[Oo][Rr](%20|\\s)*[0-9](%20|\\s)*=(%20|\\s)*[0-9]/i\";");
        sb.AppendLine($"  metadata:service http, seckit-sqli;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Web Application Attack;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:2;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSnortXss(StringBuilder sb, Vulnerability v)
    {
        var msg = $"XSS Attack — {v.Severity} finding on {v.Url}";

        sb.AppendLine($"# Rule: XSS — {v.Url} (Confidence: {v.Confidence}%)");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"{msg}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  pcre:\"/<script[^>]*>.*?</script>/i\";");
        sb.AppendLine($"  metadata:service http, seckit-xss;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Web Application Attack;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:2;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;

        sb.AppendLine($"# Rule: XSS — Event handler injection");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"XSS — Event Handler Injection (onerror/onload)\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  pcre:\"/(onerror|onload|onclick|onmouseover)\\s*=/i\";");
        sb.AppendLine($"  metadata:service http, seckit-xss;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Web Application Attack;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:2;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSnortPathTraversal(StringBuilder sb, Vulnerability v)
    {
        var msg = $"Path Traversal Attempt — {v.Severity} finding on {v.Url}";

        sb.AppendLine($"# Rule: Path Traversal — {v.Url}");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"{msg}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  pcre:\"/(\\.\\.\\/|\\.\\.\\\\\\\\)/i\";");
        sb.AppendLine($"  metadata:service http, seckit-traversal;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Attempted Administrator Privilege Gain;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;

        sb.AppendLine($"# Rule: Path Traversal — Sensitive file access");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"Path Traversal — Sensitive File Access (/etc/passwd, /etc/shadow, boot.ini)\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  pcre:\"/(/(etc\\/(passwd|shadow)|proc\\/self\\/environ|boot\\.ini))/\";");
        sb.AppendLine($"  metadata:service http, seckit-traversal;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Attempted Administrator Privilege Gain;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSnortCommandInjection(StringBuilder sb, Vulnerability v)
    {
        var msg = $"Command Injection Attempt — {v.Severity} finding on {v.Url}";

        sb.AppendLine($"# Rule: Command Injection — {v.Url}");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"{msg}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  pcre:\"/([;&|`]\\s*(cat|ls|id|whoami|wget|curl|ping|bash|sh|cmd|powershell)\\b)/i\";");
        sb.AppendLine($"  metadata:service http, seckit-cmdi;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Attempted Administrator Privilege Gain;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSnortSsrf(StringBuilder sb, Vulnerability v)
    {
        var msg = $"SSRF Attempt — {v.Severity} finding on {v.Url}";

        sb.AppendLine($"# Rule: SSRF — {v.Url}");
        sb.AppendLine($"alert tcp $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"{msg}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  pcre:\"/(url|redirect|proxy|fetch|path)=http(s)?://127\\.0\\.0\\.1/i\";");
        sb.AppendLine($"  metadata:service http, seckit-ssrf;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Attempted Information Leak;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1; priority:2;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    #endregion

    #region Suricata Rules

    private string GenerateSuricataRules(List<Vulnerability> vulns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ================================================================");
        sb.AppendLine("# Suricata IDS/IPS Rules — Generated by SecKit");
        sb.AppendLine($"# Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"# Rules generated from {vulns.Count} vulnerability findings");
        sb.AppendLine("# ================================================================");
        sb.AppendLine();

        // Suricata uses the same base format as Snort but adds app-layer support
        foreach (var v in vulns.OrderBy(v => v.Severity))
        {
            var type = v.Type.ToLowerInvariant();
            if (type is "sql injection" or "sqli")
                GenerateSuricataSqli(sb, v);
            else if (type is "xss" or "cross-site scripting")
                GenerateSuricataXss(sb, v);
            else if (type is "path traversal" or "directory traversal")
                GenerateSuricataPathTraversal(sb, v);
            else if (type is "command injection" or "os command injection")
                GenerateSuricataCommandInjection(sb, v);
            else if (type is "ssrf" or "server-side request forgery")
                GenerateSuricataSsrf(sb, v);
        }

        return sb.ToString();
    }

    private void GenerateSuricataSqli(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Suricata SQLi — {v.Url} (Confidence: {v.Confidence}%)");
        sb.AppendLine($"alert http $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"SURICATA SQL Injection — {v.Severity} finding on {v.Url}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  http.uri; content:\"union\"; nocase;");
        sb.AppendLine($"  http.uri; content:\"select\"; nocase; distance:0;");
        sb.AppendLine($"  metadata:service http, seckit-sqli;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Web Application Attack;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSuricataXss(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Suricata XSS — {v.Url}");
        sb.AppendLine($"alert http $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"SURICATA XSS Attack — {v.Severity} finding on {v.Url}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  http.uri; pcre:\"/<script[^>]*>/i\";");
        sb.AppendLine($"  metadata:service http, seckit-xss;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Web Application Attack;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSuricataPathTraversal(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Suricata Path Traversal — {v.Url}");
        sb.AppendLine($"alert http $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"SURICATA Path Traversal — {v.Severity} finding on {v.Url}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  http.uri; pcre:\"/\\.\\.\\//i\";");
        sb.AppendLine($"  metadata:service http, seckit-traversal;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Attempted Administrator Privilege Gain;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSuricataCommandInjection(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Suricata Command Injection — {v.Url}");
        sb.AppendLine($"alert http $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"SURICATA Command Injection — {v.Severity} finding on {v.Url}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  http.uri; pcre:\"/[;&|`]\\s*(cat|id|whoami|sh\\b|bash\\b)/i\";");
        sb.AppendLine($"  metadata:service http, seckit-cmdi;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Attempted Administrator Privilege Gain;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    private void GenerateSuricataSsrf(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Suricata SSRF — {v.Url}");
        sb.AppendLine($"alert http $EXTERNAL_NET any -> $HOME_NET $HTTP_PORTS (");
        sb.AppendLine($"  msg:\"SURICATA SSRF — {v.Severity} finding on {v.Url}\";");
        sb.AppendLine($"  flow:to_server,established;");
        sb.AppendLine($"  http.uri; pcre:\"/(url|redirect|proxy)=http(s)?://(127\\.0\\.0\\.1|localhost|10\\.)/i\";");
        sb.AppendLine($"  metadata:service http, seckit-ssrf;");
        sb.AppendLine($"  reference:url,{v.Url};");
        sb.AppendLine($"  classtype:Attempted Information Leak;");
        sb.AppendLine($"  sid:{_snortSid}; rev:1;");
        sb.AppendLine($")");
        sb.AppendLine();
        _snortSid++;
    }

    #endregion
}

/// <summary>Report of generated IDS rules.</summary>
public class IdsReport
{
    public string SnortPath { get; set; } = string.Empty;
    public int SnortRuleCount { get; set; }
    public string SuricataPath { get; set; } = string.Empty;
    public int SuricataRuleCount { get; set; }

    public int TotalRules => SnortRuleCount + SuricataRuleCount;
}
