using System.Text;
using System.Text.Json;
using SecKit.Core;
using SecKit.Models;

namespace SecKit.Modules.Reporting;

/// <summary>
/// Generates WAF rules (ModSecurity, Cloudflare, nginx) from vulnerability findings.
/// </summary>
public class WafGenerator
{
    private readonly string _outputDir;
    private int _ruleIdCounter = 100001;

    public WafGenerator(string outputDir)
    {
        _outputDir = Path.Combine(outputDir, "reports");
        Directory.CreateDirectory(_outputDir);
    }

    /// <summary>
    /// Generates all WAF rule sets from a list of vulnerabilities.
    /// </summary>
    public async Task<WafReport> GenerateAsync(IEnumerable<Vulnerability> vulnerabilities)
    {
        var vulns = vulnerabilities.ToList();
        var report = new WafReport();

        if (vulns.Count == 0)
        {
            Logger.Info("No vulnerabilities provided; skipping WAF rule generation.");
            return report;
        }

        // Generate ModSecurity rules
        var modSecPath = Path.Combine(_outputDir, "modsecurity.conf");
        var modSecRules = GenerateModSecurityRules(vulns);
        await File.WriteAllTextAsync(modSecPath, modSecRules);
        report.ModSecurityPath = modSecPath;
        report.ModSecurityRuleCount = modSecRules.Split('\n').Count(l => l.TrimStart().StartsWith("SecRule"));

        // Generate Cloudflare WAF rules
        var cfPath = Path.Combine(_outputDir, "cloudflare-waf.json");
        var cfRules = GenerateCloudflareRules(vulns);
        await File.WriteAllTextAsync(cfPath, cfRules);
        report.CloudflarePath = cfPath;
        report.CloudflareRuleCount = JsonDocument.Parse(cfRules).RootElement.GetArrayLength();

        // Generate nginx rate-limit config
        var nginxPath = Path.Combine(_outputDir, "nginx-rate-limit.conf");
        var nginxConfig = GenerateNginxRateLimitConfig(vulns);
        await File.WriteAllTextAsync(nginxPath, nginxConfig);
        report.NginxPath = nginxPath;

        Logger.Info($"WAF rules generated: ModSecurity={report.ModSecurityRuleCount}, Cloudflare={report.CloudflareRuleCount}");
        return report;
    }

    #region ModSecurity Rules

    private string GenerateModSecurityRules(List<Vulnerability> vulns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ================================================================");
        sb.AppendLine("# ModSecurity WAF Rules — Generated by SecKit");
        sb.AppendLine($"# Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"# Rules generated from {vulns.Count} vulnerability findings");
        sb.AppendLine("# ================================================================");
        sb.AppendLine();

        foreach (var v in vulns.OrderBy(v => v.Severity))
        {
            switch (v.Type.ToLowerInvariant())
            {
                case "sql injection":
                case "sqli":
                    GenerateModSecSqliRules(sb, v);
                    break;
                case "xss":
                case "cross-site scripting":
                    GenerateModSecXssRules(sb, v);
                    break;
                case "path traversal":
                case "directory traversal":
                    GenerateModSecPathTraversalRules(sb, v);
                    break;
                case "ssrf":
                case "server-side request forgery":
                    GenerateModSecSsrfRules(sb, v);
                    break;
            }
        }

        return sb.ToString();
    }

    private void GenerateModSecSqliRules(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Rule generated from: {v.Type} finding on {v.Url}{(string.IsNullOrEmpty(v.Parameter) ? "" : $"?{v.Parameter}=")}");
        sb.AppendLine($"# Severity: {v.Severity} | Confidence: {v.Confidence}%");
        sb.AppendLine($"# Evidence: {Truncate(v.Evidence, 120)}");
        sb.AppendLine($"SecRule ARGS \"@rx (?i)(union.*select|select.*from|insert.*into|drop\\s+table|exec\\s*\\()\" \\");
        sb.AppendLine($"  \"id:{_ruleIdCounter},phase:2,deny,status:403,msg:'SQL Injection Attempt — {v.Severity} finding on {v.Url}'\"");
        sb.AppendLine();

        _ruleIdCounter++;
        sb.AppendLine($"SecRule ARGS \"@rx (?i)((\\%27)|(')|(\\-\\-)|(\\%23)|(#))\" \\");
        sb.AppendLine($"  \"id:{_ruleIdCounter},phase:2,deny,status:403,msg:'SQL Injection — Comment/Quote Attack'\"");
        sb.AppendLine();
        _ruleIdCounter++;
    }

    private void GenerateModSecXssRules(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Rule generated from: {v.Type} finding on {v.Url}{(string.IsNullOrEmpty(v.Parameter) ? "" : $"?{v.Parameter}=")}");
        sb.AppendLine($"# Severity: {v.Severity} | Confidence: {v.Confidence}%");
        sb.AppendLine($"SecRule ARGS \"@rx (?i)(<script|javascript:|onerror\\s*=|onload\\s*=|alert\\s*\\()\" \\");
        sb.AppendLine($"  \"id:{_ruleIdCounter},phase:2,deny,status:403,msg:'XSS Attack Attempt — {v.Severity} finding on {v.Url}'\"");
        sb.AppendLine();
        _ruleIdCounter++;
    }

    private void GenerateModSecPathTraversalRules(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Rule generated from: {v.Type} finding on {v.Url}{(string.IsNullOrEmpty(v.Parameter) ? "" : $"?{v.Parameter}=")}");
        sb.AppendLine($"# Severity: {v.Severity} | Confidence: {v.Confidence}%");
        sb.AppendLine($"SecRule ARGS \"@rx (?i)(\\.\\./|\\.\\.\\\\|/etc/passwd|/etc/shadow|boot\\.ini|win\\.ini)\" \\");
        sb.AppendLine($"  \"id:{_ruleIdCounter},phase:2,deny,status:403,msg:'Path Traversal Attempt — {v.Severity} finding on {v.Url}'\"");
        sb.AppendLine();
        _ruleIdCounter++;
    }

    private void GenerateModSecSsrfRules(StringBuilder sb, Vulnerability v)
    {
        sb.AppendLine($"# Rule generated from: {v.Type} finding on {v.Url}{(string.IsNullOrEmpty(v.Parameter) ? "" : $"?{v.Parameter}=")}");
        sb.AppendLine($"# Severity: {v.Severity} | Confidence: {v.Confidence}%");
        sb.AppendLine($"SecRule ARGS \"@rx (?i)(http://(localhost|127\\.0\\.0\\.1|10\\.|172\\.(1[6-9]|2\\d|3[01])\\.|192\\.168\\.|169\\.254\\.|0\\.0\\.0\\.0)|file://|gopher://)\" \\");
        sb.AppendLine($"  \"id:{_ruleIdCounter},phase:2,deny,status:403,msg:'SSRF Attempt — Internal/Private IP Access'\"");
        sb.AppendLine();
        _ruleIdCounter++;
    }

    #endregion

    #region Cloudflare WAF Rules

    private string GenerateCloudflareRules(List<Vulnerability> vulns)
    {
        var rules = new List<object>();
        int cfRuleId = 1;

        foreach (var v in vulns)
        {
            switch (v.Type.ToLowerInvariant())
            {
                case "sql injection":
                case "sqli":
                    rules.Add(new
                    {
                        id = $"seckit-sqli-{cfRuleId++}",
                        description = $"SQL Injection block — {v.Severity} finding on {v.Url}",
                        expression = $"(http.request.uri.query contains \"union\" and http.request.uri.query contains \"select\") or (http.request.uri.query contains \"'--\") or (http.request.uri.query contains \"1=1\")",
                        action = "block",
                        enabled = true
                    });
                    break;
                case "xss":
                case "cross-site scripting":
                    rules.Add(new
                    {
                        id = $"seckit-xss-{cfRuleId++}",
                        description = $"XSS block — {v.Severity} finding on {v.Url}",
                        expression = $"(http.request.uri.query contains \"<script\") or (http.request.uri.query contains \"javascript:\") or (http.request.uri.query contains \"onerror=\")",
                        action = "block",
                        enabled = true
                    });
                    break;
                case "path traversal":
                case "directory traversal":
                    rules.Add(new
                    {
                        id = $"seckit-traversal-{cfRuleId++}",
                        description = $"Path Traversal block — {v.Severity} finding on {v.Url}",
                        expression = $"(http.request.uri.path contains \"../\") or (http.request.uri.path contains \"..\\\\\")",
                        action = "block",
                        enabled = true
                    });
                    break;
                case "ssrf":
                case "server-side request forgery":
                    rules.Add(new
                    {
                        id = $"seckit-ssrf-{cfRuleId++}",
                        description = $"SSRF block — {v.Severity} finding on {v.Url}",
                        expression = $"(http.request.uri.query contains \"http://localhost\") or (http.request.uri.query contains \"http://127.0.0.1\") or (http.request.uri.query contains \"http://169.254\")",
                        action = "block",
                        enabled = true
                    });
                    break;
            }
        }

        return JsonSerializer.Serialize(rules, new JsonSerializerOptions { WriteIndented = true });
    }

    #endregion

    #region Nginx Rate-Limit Config

    private string GenerateNginxRateLimitConfig(List<Vulnerability> vulns)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# ================================================================");
        sb.AppendLine("# nginx Rate-Limit Configuration — Generated by SecKit");
        sb.AppendLine($"# Generated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("# ================================================================");
        sb.AppendLine();

        // Check for auth-related findings (brute force / credential testing)
        var authVulns = vulns.Where(v =>
            v.Type.ToLowerInvariant() == "auth" || v.Type.ToLowerInvariant() == "authentication" || v.Type.ToLowerInvariant() == "brute force" ||
            v.Type.ToLowerInvariant().Contains("credential")).ToList();

        var otherVulns = vulns.Where(v =>
            v.Severity == "Critical" || v.Severity == "High" || v.Severity == "Medium").ToList();

        sb.AppendLine("# Define a shared memory zone for rate limiting");
        sb.AppendLine("limit_req_zone $binary_remote_addr zone=seckit_login:10m rate=5r/m;");
        sb.AppendLine("limit_req_zone $binary_remote_addr zone=seckit_api:10m rate=30r/m;");
        sb.AppendLine("limit_req_zone $binary_remote_addr zone=seckit_general:10m rate=60r/m;");
        sb.AppendLine();

        if (authVulns.Count > 0)
        {
            sb.AppendLine($"# Rate limiting for authentication endpoints — {authVulns.Count} auth-related findings detected");
            sb.AppendLine("# Apply to locations: /login, /auth, /signin, /api/auth, etc.");
            sb.AppendLine("location ~ ^/(login|auth|signin|api/auth) {");
            sb.AppendLine("    limit_req zone=seckit_login burst=3 nodelay;");
            sb.AppendLine($"    limit_req_status 429;  # Too Many Requests");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        if (otherVulns.Count > 0)
        {
            sb.AppendLine($"# General API rate limiting — {otherVulns.Count} vulnerability findings warrant throttling");
            sb.AppendLine("location /api/ {");
            sb.AppendLine("    limit_req zone=seckit_api burst=10 nodelay;");
            sb.AppendLine("    limit_req_status 429;");
            sb.AppendLine("    # Block common attack patterns based on findings");
            foreach (var v in otherVulns.Take(5))
            {
                sb.AppendLine($"    # {v.Type} finding on {v.Url} — {v.Severity}");
            }
            sb.AppendLine("}");
            sb.AppendLine();
        }

        sb.AppendLine("# Connection limiting (DDoS mitigation)");
        sb.AppendLine("limit_conn_zone $binary_remote_addr zone=seckit_conn:10m;");
        sb.AppendLine("limit_conn seckit_conn 20;");
        sb.AppendLine();

        sb.AppendLine("# Global rate limiting for all locations");
        sb.AppendLine("location / {");
        sb.AppendLine("    limit_req zone=seckit_general burst=20 nodelay;");
        sb.AppendLine("    limit_req_status 429;");
        sb.AppendLine("}");

        return sb.ToString();
    }

    #endregion

    private static string Truncate(string value, int maxLength)
        => string.IsNullOrEmpty(value) ? "N/A" :
           value.Length <= maxLength ? value : value[..maxLength] + "...";
}

/// <summary>Report of generated WAF rules.</summary>
public class WafReport
{
    public string ModSecurityPath { get; set; } = string.Empty;
    public int ModSecurityRuleCount { get; set; }
    public string CloudflarePath { get; set; } = string.Empty;
    public int CloudflareRuleCount { get; set; }
    public string NginxPath { get; set; } = string.Empty;

    public int TotalRules => ModSecurityRuleCount + CloudflareRuleCount;
}
